services:
  - type: web
    name: jawebni-site
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --workers 3 --threads 4 --timeout 120
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASS
        sync: false
      - key: ADMIN_NOTIFICATION_EMAIL
        sync: false
      - key: GOOGLE_WEBHOOK_URL
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
